### ISSUE TITLE
Why the input format is RGB and not the default BGR？

### ISSUE THREAD

**Issue by Henryluoluoluo** [Shengcao-Cao/CMT#10]
In **faster_rcnn_VGG_cross_city.yaml** the input format is RGB. I trained on my own data set and found that this parameter has a great impact on the experimental results.
```
  UNSUP_LOSS_WEIGHT: 1.0
  SUP_LOSS_WEIGHT: 1.0
  DIS_TYPE: "vgg4" #["concate","p2","multi"]
TEST:
  EVAL_PERIOD: 1000
INPUT:
  FORMAT: "RGB"
```
